version: "3"
services:
  web:
    image: web:1.0
    restart: always
    ports:
      - "8080:80"

  server:
    image: server:1.0
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongodb:db

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
